### ISSUE TITLE
csproj file need to update sdk version

### ISSUE THREAD

**Issue by HaoHoo** [MicrosoftDocs/mslearn-expose-hybrid-services-with-azure-relay#2]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>

The TargetFramework should be ‘netcoreapp3.1’ to fit the Azure runtime version 3.1.9.

I just change that two file and pass the error and run the sample code successfully.

**Comment by Kai-lash** [comment]
Agreed. This is the MS learn module: https://docs.microsoft.com/en-us/learn/modules/expose-hybrid-services-with-azure-relay.
After making the above changes, the exercise in that module needs to be updated to use these commands to run it:
- dotnet bin/Debug/netcoreapp3.1/sender.dll
- dotnet bin/Debug/netcoreapp3.1/listener.dll

**Comment by patridge** [comment]
Thank you for reporting this. A combination of #3 and a content update should have this module working again.
